### ISSUE TITLE
Add meaningful comment

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/discord-file-storage#1]
Add comment `#Add your discord channel id here` to line number 12 in file `fs.py`

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says ` Fixes #1`

Step for completing the task:

 1. Fork the repo
 2. Make you necessary changes in `fs.py`
 3. Submit a PR

Leave a star if you like the project!

**Comment by warmachine028** [comment]
I want to work on this issue , can you assign me

**Comment by priyanshbalyan** [comment]
@warmachine028 Sure. I'll merge your PR when hacktober starts

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by priyanshbalyan** [comment]
@aniket-24 you can pickup https://github.com/priyanshbalyan/discord-file-storage/issues/2 if you want

**Comment by aniket-24** [comment]
> @aniket-24 you can pickup #2 if you want

Okay, assign me!
