### ISSUE TITLE
Fix download command bug

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/discord-file-storage#6]
Discord removes special characters on uploading a file to a channel. Currently the download command fails if uploaded file contains `(` or `)`.

To fix this define a new variable `fileRegex = r'&|\+|\(|\)'` on line no. 223 in file `fs.py` and replace the first parameter of re.sub with it on line no. 226 i.e. replace `re.sub(r'&|\+', '', file['filename'])` with `re.sub(fileRegex, '', file['filename'])`

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says `Fixes #6`

Step for completing the task:

1. Fork the repo
2. Make you necessary changes in fs.py
3. Submit a PR

Leave a star if you like the project!

**Comment by Rutujabadve** [comment]
I would like to work on this

**Comment by priyanshbalyan** [comment]
@Rutujabadve Go ahead
